trigger:
- ci-cd-azure-pipeline
  
variables:
  buildConfiguration: 'Release'
stages:
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
- template: templates/deploy.yml
  parameters:
    buildConfiguration: 'Release'
    webAppName: '$(WebAppName)'
    sqlDatabaseName: $(sqlDatabaseName)
    sqlServerAdministratorLogin: $(SqlServerAdministratorLogin)
    sqlServerFullyQualifiedDomainName: $(SqlServerFullyQualifiedDomainName)
    sqlServerAdministratorLoginPassword: $(SqlServerAdministratorLoginPassword)
    environment: dev
    variablesGroup: Release
- template: templates/deploy.yml
  parameters:
    buildConfiguration: 'Release'
    webAppName: '$(WebAppName)'
    sqlDatabaseName: $(SqlDatabaseName)
    sqlServerAdministratorLogin: $(SqlServerAdministratorLogin)
    sqlServerFullyQualifiedDomainName: $(SqlServerFullyQualifiedDomainName)
    sqlServerAdministratorLoginPassword: $(SqlServerAdministratorLoginPassword)
    environment: test
    variablesGroup: Test