trigger:
- ci-cd-azure-pipeline
  
variables:
  buildConfiguration: 'Release'
stages:
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
- template: templates/deploy.yml
  parameters:
    buildConfiguration: 'Release'