version: '3.4'

services:
    # web api service
  todolist.webapi:
    #container_name: todo-list-webapi-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:80"

  # database service
  todolist.mssql-server:
    #container_name: todo-list-mssql-server-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyC0m9l&xP@ssw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-server-linux-data-workshop:/var/opt/mssql/data
 
volumes:
  mssql-server-linux-data-workshop: