version: '3.4'

services:
  todolist.webapi:
    image: ${DOCKER_REGISTRY-}/todo-list-web-api
    build:
      context: .
      dockerfile: TodoList.WebApi/Dockerfile
    depends_on:
      - todolist.mssql-server
      
    networks:
      - TodoList_network  
     # database service
  todolist.mssql-server:
    image: ${DOCKER_REGISTRY-}/todo-list.mssql-server
    build:
      context: TodoList.Database/Docker
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: MyC0m9l&xP@ssw0rd
    networks:
      - TodoList_network      

networks:
  TodoList_network:
    