apiVersion: v1
kind: Service
metadata:
  name: workshop-todolist-db-service
  labels:
    version: 1.0.0
    product: workshop-todolist-db
    environment:  dev
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer