kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk
  labels:
    version: 1.0.0
    product: workshop-todolist-db
    environment:  dev
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
    version: 1.0.0
    product: workshop-todolist-db
    environment:  dev
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi