apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-todolist-db-deployment
   
  labels:
    version: 1.0.0
    product: workshop-todolist-db
    environment:  dev
spec:
  replicas: 1
  selector:
     matchLabels:
       app: workshop-todolist-db
       env:  dev
  template:
    metadata:
      labels:
       app: workshop-todolist-db
       env:  dev
    spec:
      containers:
      - name: db-domainservice
        image: mcr.microsoft.com/mssql/server:2019-latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes: 
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-pvc
     